<?php


use app\admin\domian\Alias;
use app\admin\model\AliasModel;
use PHPUnit\Framework\TestCase;

class AliasTest extends TestCase
{
    private static $alias;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $data = array(
            'daima'=>'13527'
        ,'jiaotongfangshi'=>'K33'
        ,'shiyongxingzhi'=>'R'
        ,'night'=>0
        ,'weifajifengshu'=>'3');

        self::$alias = new Alias($data);
    }

    public function testGetNight()
    {
        $this->assertEquals(false,self::$alias->getNight());

    }

    public function testGenerateMultiAlias()
    {
        $model = new AliasModel();
        $result = $model->getAliasByName('超速');
        $multiAlias = array();
        foreach ($result as $k => $v)
        {
            $multiAlias[] = new Alias($v);

        }
        $this->assertGreaterThan(10,count($multiAlias),'no alias was generate,check database connect');
    }
}
