<?php


use app\admin\domian\Alias;
use PHPUnit\Framework\TestCase;

class AliasTest extends TestCase
{
    private static $alias;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $data = array(
            'daima'=>'13527'
        ,'jiaotongfangshi'=>'K33'
        ,'shiyongxingzhi'=>'R'
        ,'night'=>0
        ,'weifajifenshu'=>'3');

        self::$alias = new Alias($data);
    }

    public function testGetNight()
    {
        $this->assertEquals(false,self::$alias->getNight());

    }

    public function testGetShiyongxingzhi()
    {

    }
}
